{% set name = "grpcio-status" %}
{% set version = "1.62.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-status-{{ version }}.tar.gz
  sha256: 62e1bfcb02025a1cd73732a2d33672d3e9d0df4d21c12c51e0bbcaf09bab742a

build:
  number: 0
  skip: true  # [py<36]
  skip: true  # [linux and s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - protobuf >=4.21.6
    - grpcio >=1.62.2
    - googleapis-common-protos >=1.5.5

test:
  imports:
    - grpc_status
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://grpc.io
  summary: Status proto mapping for gRPC
  description: |
    Reference package for GRPC Python status proto mapping.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://grpc.github.io/grpc/python/index.html
  dev_url: https://github.com/grpc/grpc/tree/master/src/python/grpcio_status

extra:
  recipe-maintainers:
    - hadim
